config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'sessions#new'
    post 'sessions/create' => 'sessions#create'
    resources :admin_users
    resources :prizes
  end

  root to: 'subscribers#new'
  resources :subscribers, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/prizes_controller.rb
module Admin
  class PrizesController < ApplicationController
    before_action :authenticate!
    before_action :set_prize, only: [:show, :edit, :update, :destroy]

    # GET /prizes
    # GET /prizes.json
    def index
      @prizes = Prize.all
    end

    # GET /prizes/1
    # GET /prizes/1.json
    def show
    end

    # GET /prizes/new
    def new
      @prize = Prize.new
    end

    # GET /prizes/1/edit
    def edit
    end

    # POST /prizes
    # POST /prizes.json
    def create
      @prize = Prize.new(prize_params)

      respond_to do |format|
        if @prize.save
          format.html { redirect_to admin_prize_url(@prize), notice: 'Prize was successfully created.' }
          format.json { render :show, status: :created, location: @prize }
        else
          format.html { render :new }
          format.json { render json: @prize.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /prizes/1
    # PATCH/PUT /prizes/1.json
    def update
      respond_to do |format|
        if @prize.update(prize_params)
          format.html { redirect_to admin_prize_url(@prize), notice: 'Prize was successfully updated.' }
          format.json { render :show, status: :ok, location: @prize }
        else
          format.html { render :edit }
          format.json { render json: @prize.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /prizes/1
    # DELETE /prizes/1.json
    def destroy
      @prize.update_attributes(active: false)
      respond_to do |format|
        format.html { redirect_to admin_prizes_url, notice: 'Prize was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_prize
        @prize = Prize.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def prize_params
        params.require(:prize).permit(:prize, :stock,
                                      prize_conditions_attributes: [:id, :condition_type, :after_subscribers, :condition_values, :inactive])
      end
  end
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/views/admin/prizes/_form.html.erb
<%= form_for(@prize, url: admin_prize_path(id: @prize.id || ''), html: { class: "form" }) do |form| %>
  <% if prize.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prize.errors.count, "error") %> prohibited this prize from being saved:</h2>

      <ul>
      <% prize.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prize %>
    <%= form.text_field :prize, id: :prize_prize %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock, id: :prize_stock %>
  </div>

  <div class="field">
    <p>Conditions: </p>
    <%= form.fields_for :prize_conditions do |prize_condition_form| %>
      <p>
          Condition type <%= prize_condition_form.select :condition_type, options_for_select(["", "equal", "multiple"], prize_condition_form.object.condition_type) %>
          Values <%= prize_condition_form.text_field :condition_values %>
          after subscriber number <%= prize_condition_form.number_field :after_subscribers %>
      </p>
    <% end %>
  </div>

  <div class="field">
    <%= submit_tag "Add condition", :type => 'button', :id => 'addCondition',
          :onclick => 'addConditionField()' %>

    <div id="condition" style="display: none">
      <p>Create multiple condition values for the same condition adding values separated by space.</p>
    </div>

    <div id="myList" class="form-group">
    </div>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  function addConditionField() {

    var date = new Date();

    var mSec = date.getTime();

    idAttributConditionType =
          "prize_prize_conditions_attributes_0_condition_type".replace("0", mSec);
    nameAttributConditionType =
          "prize[prize_conditions_attributes][0][condition_type]".replace("0", mSec);

    idAttributeConditionValues =
          "prize_prize_conditions_attributes_0_condition_values".replace("0", mSec);
    nameAttributeConditionValues =
          "prize[prize_conditions_attributes][0][condition_values]".replace("0", mSec);

    idAttributeAfterSubscribers =
          "prize_prize_conditions_attributes_0_after_subscribers".replace("0", mSec);
    nameAttributeAfterSubscribers =
          "prize[prize_conditions_attributes][0][after_subscribers]".replace("0", mSec);

    var div = document.createElement("div");
    div.setAttribute("class", "condition-div")

    var labelConditionType = document.createElement("label");
    labelConditionType.setAttribute("for", idAttributConditionType);
    var conditionTypeLabelText = document.createTextNode("Condition type");
    labelConditionType.appendChild(conditionTypeLabelText);
    div.appendChild(labelConditionType);

    var inputConditionType = document.createElement("SELECT");
    inputConditionType.setAttribute("type", "select");
    inputConditionType.setAttribute("id", idAttributConditionType);
    inputConditionType.setAttribute("name", nameAttributConditionType);
    div.appendChild(inputConditionType);
    var array_opt = ["", "equal", "multiple"]
    for (var i = 0; i < array_opt.length; i++) {
        var option = document.createElement("option");
        option.value = array_opt[i];
        option.text = array_opt[i];
        inputConditionType.appendChild(option);
    }

    var labelConditionValues = document.createElement("label");
    labelConditionValues.setAttribute("for", idAttributeConditionValues);
    var ConditionValuesLabelText = document.createTextNode("values");
    labelConditionValues.appendChild(ConditionValuesLabelText);
    div.appendChild(labelConditionValues);

    var inputConditionValues = document.createElement("INPUT");
    inputConditionValues.setAttribute("type", "text");
    inputConditionValues.setAttribute("placeholder", "e.g: 10 50 100 500");
    inputConditionValues.setAttribute("id", idAttributeConditionValues);
    inputConditionValues.setAttribute("name", nameAttributeConditionValues);
    div.appendChild(inputConditionValues);

    var labelAfterSubscribers = document.createElement("label");
    labelAfterSubscribers.setAttribute("for", idAttributeAfterSubscribers);
    var AfterSubscribersLabelText = document.createTextNode("after subscriber number");
    labelAfterSubscribers.appendChild(AfterSubscribersLabelText);
    div.appendChild(labelAfterSubscribers);

    var inputAfterSubscribers = document.createElement("INPUT");
    inputAfterSubscribers.setAttribute("type", "number");
    inputAfterSubscribers.setAttribute("id", idAttributeAfterSubscribers);
    inputAfterSubscribers.setAttribute("name", nameAttributeAfterSubscribers);
    div.appendChild(inputAfterSubscribers);

    document.getElementById("myList").appendChild(div);

    document.getElementById("condition").setAttribute("style", "display: block");
  }
</script>

<style type="text/css">
  label {
    display: inline;
    margin: 10px;
  }

  .condition-div {
    margin: 10px;
  }
</style>

app/views/admin/prizes/edit.html.erb
<h1>Editing Prize</h1>

<%= render 'form', prize: @prize %>

<%= link_to 'Show', admin_prize_path(@prize) %> |
<%= link_to 'Back', admin_prizes_path %>

app/views/admin/prizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prizes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Prize</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prizes.each do |prize| %>
      <tr>
        <td><%= prize.prize %></td>
        <td><%= prize.stock %></td>
        <td><%= link_to 'Show', admin_prize_path(prize) %></td>
        <td><%= link_to 'Edit', edit_admin_prize_path(prize) %></td>
        <td><%= link_to 'Destroy', admin_prize_path(prize), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prize', new_admin_prize_path %>

app/views/admin/prizes/new.html.erb
<h1>New Prize</h1>

<%= render 'form', prize: @prize %>

<%= link_to 'Back', admin_prizes_path %>

app/views/admin/prizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prize:</strong>
  <%= @prize.prize %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @prize.stock %>
</p>

<%= link_to 'Edit', edit_admin_prize_path(@prize) %> |
<%= link_to 'Back', admin_prizes_path %>