config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'sessions#new'
    post 'sessions/create' => 'sessions#create'
    resources :admin_users
    resources :prizes
  end

  root to: 'subscribers#new'
  resources :subscribers, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
	has_secure_password

	validates_uniqueness_of :username, :email
  validates :email, presence: true, format:{ with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :password,  length: { minimum: 8 }
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < ApplicationController
    before_action :authenticate!
    before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

    # GET /admin_users
    # GET /admin_users.json
    def index
      @admin_users = AdminUser.all
    end

    # GET /admin_users/1
    # GET /admin_users/1.json
    def show
    end

    # GET /admin_users/new
    def new
      @admin_user = AdminUser.new
    end

    # GET /admin_users/1/edit
    def edit
    end

    # POST /admin_users
    # POST /admin_users.json
    def create
      @admin_user = AdminUser.new(admin_user_params)

      respond_to do |format|
        if @admin_user.save
          format.html { redirect_to admin_admin_user_url(@admin_user), notice: 'Admin user was successfully created.' }
          format.json { render :show, status: :created, location: @admin_user }
        else
          format.html { render :new }
          format.json { render json: @admin_user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin_users/1
    # PATCH/PUT /admin_users/1.json
    def update
      respond_to do |format|
        if @admin_user.update(admin_user_params)
          format.html { redirect_to admin_admin_user_url(@admin_user), notice: 'Admin user was successfully updated.' }
          format.json { render :show, status: :ok, location: @admin_user }
        else
          format.html { render :edit }
          format.json { render json: @admin_user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin_users/1
    # DELETE /admin_users/1.json
    def destroy
      @admin_user.destroy
      respond_to do |format|
        format.html { redirect_to admin_admin_users_url, notice: 'Admin user was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_user
        @admin_user = AdminUser.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def admin_user_params
        params.require(:admin_user).permit(:username, :email, :password, :password_confirmation)
      end
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin/admin_users/_form.html.erb
<%= form_for(@admin_user, url: admin_admin_user_path(id: @admin_user.id || ''), local: true ) do |form| %>
  <% if admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% admin_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :admin_user_username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :admin_user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :admin_user_password%>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password, id: :admin_user_password_confirmation%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/admin_users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Show', admin_admin_users_path(@admin_user) %> |
<%= link_to 'Back', admin_admin_users_path %>

app/views/admin/admin_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.username %></td>
        <td><%= admin_user.email %></td>
        <td><%= link_to 'Show', admin_admin_user_path(admin_user) %></td>
        <td><%= link_to 'Edit', edit_admin_admin_user_path(admin_user) %></td>
        <td><%= link_to 'Destroy', admin_admin_user_path(admin_user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin User', new_admin_admin_user_path %>

app/views/admin/admin_users/new.html.erb
<h1>New Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Back', admin_admin_users_path %>

app/views/admin/admin_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @admin_user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_user.email %>
</p>

<p>
  <strong>Password :</strong>
  <%= @admin_user.password %>
</p>

<p>
  <strong>Password Confirmation:</strong>
  <%= @admin_user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_admin_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_admin_users_path %>